### PR TITLE
Edited remove function

### PR DESCRIPTION
**Pull request by Reem-w**
I Edited the remove function logic a little bit  , just to try making a pull request.

I commented your implementation

### CODE REVIEW

**Review by MohamedSaid7102 — COMMENTED** [review]
@Reem-w 

1. Did you test your new implementation?
2. Is this Awesome code yours? did you write or copy it? 😃

**Comment by Reem-w** [comment]
>

**Comment by Reem-w** [comment]
@MohamedSaid7102 
Yes and There are some test cases in index file 

Thanks, I wrote it

**Comment by MohamedSaid7102** [comment]
@Reem-w Welcome to GitHub teamwork 🚀 🎉

**Pull request merged**
